export interface PdfDesignReference {
  id: string;
  name: string;
  family: string;
  tags: string[];
  summary: string;
  typography: string;
  composition: string;
  palette: string;
  surfaces: string;
  imagery: string;
  tables: string;
  avoid: string;
}

export const PDF_DESIGN_LIBRARY: PdfDesignReference[] = [
  {
    id: 'restrained-editorial-brief',
    name: 'Restrained Editorial Brief',
    family: 'editorial',
    tags: ['polished','brief','overview','executive','professional','editorial','technology','business'],
    summary: 'Quiet, premium editorial hierarchy with a strong opening treatment, restrained accents, and varied section composition.',
    typography: 'Confident sans or restrained serif/sans pairing; title is prominent but not theatrical; body copy has comfortable measure and leading.',
    composition: 'Use a deliberate opening band or title area, then mix open text, small diagrams, columns, and one or two structured surfaces. Avoid repeating one module everywhere.',
    palette: 'White/ivory base, dark ink/navy anchor, one muted accent and at most one secondary accent.',
    surfaces: 'Rules, whitespace, and alignment before boxes. Cards only when they genuinely clarify grouped concepts.',
    imagery: 'Editorial illustrations or diagrams should feel integrated into the page rather than dropped into a dashboard.',
    tables: 'Quiet rules, strong header hierarchy, generous row spacing; avoid spreadsheet heaviness.',
    avoid: 'Rainbow accents, equal card grids for every section, app-dashboard styling, oversized callout boxes.',
  },
  {
    id: 'consulting-strategy',
    name: 'Consulting / Strategy Report',
    family: 'business',
    tags: ['consulting','strategy','executive','business','management','recommendation','analysis','corporate'],
    summary: 'Structured business communication with crisp hierarchy, clear takeaway logic, and restrained visual emphasis.',
    typography: 'Neutral sans; decisive headings; compact explanatory text; strong distinction between headline, evidence, and implication.',
    composition: 'Headline-led pages, two-column logic, simple matrices, concise callouts, and clear section bands where useful.',
    palette: 'Mostly white with navy/charcoal and one firm accent.',
    surfaces: 'Use boxes selectively for key findings; most hierarchy should come from spacing, rules, and alignment.',
    imagery: 'Simple analytical diagrams and charts, not decorative illustrations.',
    tables: 'Compact and action-oriented; highlight only the most important row/column.',
    avoid: 'Marketing gradients, playful icons, excessive rounded corners, dense decorative backgrounds.',
  },
  {
    id: 'swiss-international',
    name: 'Swiss / International Typographic',
    family: 'modernist',
    tags: ['swiss','minimal','modernist','clean','grid','typography','minimalist','design'],
    summary: 'Rigorous grid, asymmetric balance, strong typography, ample white space, and minimal decoration.',
    typography: 'Sans-serif, disciplined scale system, often left aligned; hierarchy through weight, size, and spacing rather than effects.',
    composition: 'Strong underlying grid; asymmetric but balanced arrangements; sections may span or offset columns.',
    palette: 'Black/white with one precise accent, often red, blue, or muted green.',
    surfaces: 'Almost no cards; use rules, blocks of type, and alignment.',
    imagery: 'Cropping and placement are intentional; diagrams are geometric and sparse.',
    tables: 'Hairline rules and excellent alignment; keep visual noise low.',
    avoid: 'Rounded-card dashboards, shadows, gradients, decorative badges, symmetrical module repetition.',
  },
  {
    id: 'annual-report',
    name: 'Annual Report',
    family: 'corporate',
    tags: ['annual','report','company','corporate','year','results','performance','stakeholder','sustainability'],
    summary: 'Polished corporate publication balancing narrative, key metrics, tables, and selective visual storytelling.',
    typography: 'Professional sans or serif/sans pair; strong chapter headings; numerals given visual prominence where meaningful.',
    composition: 'Hero opener, metric moments, narrative sections, tables/charts, and occasional full-width visual breaks.',
    palette: 'Brand-aware but controlled; 1–2 accents on a neutral foundation.',
    surfaces: 'Mix open editorial space with structured metric panels; do not turn every fact into a tile.',
    imagery: 'Photography or illustrations can be large and purposeful.',
    tables: 'Readable, publication-like, with strong header contrast and clear numeric alignment.',
    avoid: 'Generic startup dashboard look, excessive badges, every section in the same card shape.',
  },
  {
    id: 'technical-whitepaper',
    name: 'Technical White Paper',
    family: 'technical',
    tags: ['technical','whitepaper','engineering','architecture','ai','software','science','systems','research'],
    summary: 'Clear, credible technical publication where diagrams, hierarchy, and readable prose matter more than decoration.',
    typography: 'Neutral sans or serif body with clear sans headings; code/technical labels may use mono sparingly.',
    composition: 'Strong title area, explanatory sections, architecture diagrams, tables, and occasional side notes.',
    palette: 'White, charcoal/navy, one technical accent such as teal or cobalt.',
    surfaces: 'Use panels only for definitions, architecture summaries, or warnings.',
    imagery: 'Diagrams should be informative, labelled, and visually quiet.',
    tables: 'Structured, precise, and easy to scan; avoid cramped cells.',
    avoid: 'Marketing copy aesthetics, loud gradients, decorative hero art without informational value.',
  },
  {
    id: 'institutional-report',
    name: 'Institutional / Government Report',
    family: 'institutional',
    tags: ['government','institutional','policy','public','official','report','administration','regulatory'],
    summary: 'Authoritative, conservative publication with excellent readability and minimal visual theatrics.',
    typography: 'Highly legible serif or sans; conservative hierarchy; strong heading discipline.',
    composition: 'Straightforward sections, side-by-side facts where useful, clear numbered recommendations, restrained tables.',
    palette: 'White with dark blue/charcoal and a muted institutional accent.',
    surfaces: 'Minimal; use shaded note boxes sparingly.',
    imagery: 'Charts/maps/diagrams only when useful; avoid decorative illustration.',
    tables: 'Strongly legible with restrained shading and clear headers.',
    avoid: 'SaaS cards, gradients, playful iconography, excessive colour.',
  },
  {
    id: 'academic-journal',
    name: 'Academic Journal / Research Paper',
    family: 'academic',
    tags: ['academic','journal','research','paper','study','methodology','literature','university','scholarly'],
    summary: 'Scholarly, text-led, disciplined and citation-friendly with restrained visual hierarchy.',
    typography: 'Serif body with modest sans or serif headings; comfortable line length; footnote/citation-friendly.',
    composition: 'Title/author area, abstract-like intro, sectional prose, figures and tables placed deliberately.',
    palette: 'Primarily black/white; one restrained accent at most.',
    surfaces: 'Avoid cards; use headings, captions, rules, and figure/table framing.',
    imagery: 'Figures and diagrams should look publication-ready and evidence-led.',
    tables: 'Booktabs-like restraint; clear captions; no heavy grid unless necessary.',
    avoid: 'Marketing styling, coloured tiles, oversized banners, glossy UI components.',
  },
  {
    id: 'legal-memo',
    name: 'Legal Memorandum',
    family: 'legal',
    tags: ['legal','memo','memorandum','law','counsel','case','contract','compliance'],
    summary: 'Conservative, text-forward legal document with unmistakable hierarchy and zero decorative noise.',
    typography: 'Readable serif or restrained sans; clear headings; compact but comfortable body text.',
    composition: 'Memo header, issue/rule/analysis/conclusion structure, numbered headings, indented quotations where needed.',
    palette: 'Black/white, possibly one dark blue accent for rules or headings.',
    surfaces: 'Almost none; light note boxes only for exceptional cautions.',
    imagery: 'Rare; only substantive diagrams or evidence figures.',
    tables: 'Plain, aligned, and conservative.',
    avoid: 'Colourful cards, gradients, decorative banners, playful shapes, startup aesthetics.',
  },
  {
    id: 'japanese-corporate',
    name: 'Japanese Corporate Document',
    family: 'japanese',
    tags: ['japanese','japan','corporate','business','proposal','company','jp','formal'],
    summary: 'White-dominant, orderly Japanese business-document language with restrained colour and precise alignment.',
    typography: 'Japanese sans/Mincho as appropriate; compact hierarchy; clear information density without decorative excess.',
    composition: 'Structured headings, tables, aligned information blocks, strong spacing discipline and conventional ordering.',
    palette: 'Black/charcoal on white; restrained navy/grey or company colour only where useful.',
    surfaces: 'Flat, squared, and functional; minimal rounding/shadows.',
    imagery: 'Small and purposeful; diagrams are clean and information-first.',
    tables: 'Prominent and carefully aligned; borders may be slightly stronger than Western editorial styles.',
    avoid: 'SaaS cards, gradients, oversized English-style hero banners, playful decoration.',
  },
  {
    id: 'japanese-rirekisho',
    name: 'Japanese Rirekisho / Shokumukeirekisho',
    family: 'cv',
    tags: ['japanese','cv','resume','rirekisho','shokumukeirekisho','job','career','employment'],
    summary: 'Conventional Japanese employment-document structure: white, restrained, information-dense, and highly aligned.',
    typography: 'Japanese system-like fonts; modest hierarchy; no decorative display type.',
    composition: 'Clear personal-information zones, chronological tables, qualifications, skills, and concise narrative blocks.',
    palette: 'Black/white; optional subtle grey or navy rules.',
    surfaces: 'Square cells and rules rather than cards.',
    imagery: 'Passport-style headshot area only when appropriate.',
    tables: 'Central visual structure; exact alignment and predictable row rhythm.',
    avoid: 'Colourful resume templates, icons for every field, rounded boxes, marketing-style personal branding.',
  },
  {
    id: 'korean-corporate',
    name: 'Korean Corporate Document',
    family: 'korean',
    tags: ['korean','korea','corporate','business','formal','kr'],
    summary: 'Clean, structured East-Asian corporate document with compact hierarchy and restrained visual treatment.',
    typography: 'Highly legible Korean sans; compact headings and strong alignment.',
    composition: 'Ordered sections, clean tables, information bands, disciplined whitespace.',
    palette: 'White/charcoal with muted blue or brand accent.',
    surfaces: 'Flat and functional.',
    imagery: 'Purposeful diagrams or headshot only where conventional.',
    tables: 'Strong, regular grid and clear labelling.',
    avoid: 'Decorative SaaS visuals, excessive rounding, loud colour.',
  },
  {
    id: 'european-minimal-cv',
    name: 'European Minimal CV',
    family: 'cv',
    tags: ['cv','resume','european','minimal','career','job','professional'],
    summary: 'Elegant one- or two-page CV with strong typographic hierarchy and restrained personal branding.',
    typography: 'Clean sans or serif/sans pair; name prominent, section headings subtle.',
    composition: 'Balanced single or two-column layout; chronology and achievements prioritized.',
    palette: 'Mostly monochrome with one muted accent.',
    surfaces: 'Little to no card UI; use columns, rules, spacing, and alignment.',
    imagery: 'Optional professional headshot depending on locale/context.',
    tables: 'Rare; skills/languages may use restrained aligned lists.',
    avoid: 'Progress bars, icon overload, colourful boxes, dashboard resume styling.',
  },
  {
    id: 'traditional-resume',
    name: 'Traditional Resume',
    family: 'cv',
    tags: ['resume','cv','job','career','traditional','ats','employment'],
    summary: 'Conservative, ATS-friendly resume with excellent hierarchy and no decorative distractions.',
    typography: 'Readable sans or serif; strong name, simple section headings.',
    composition: 'Single column, concise bullets, clear chronology.',
    palette: 'Black/white or very subtle dark accent.',
    surfaces: 'None.',
    imagery: 'Usually none unless user requests.',
    tables: 'Avoid unless necessary.',
    avoid: 'Cards, columns that hurt reading order, icons, graphics, gradients.',
  },
  {
    id: 'portfolio-cv',
    name: 'Contemporary Portfolio CV',
    family: 'cv',
    tags: ['portfolio','cv','resume','creative','designer','architect','artist','career'],
    summary: 'More expressive CV/portfolio hybrid with editorial spacing and selective visual identity.',
    typography: 'Distinctive but readable; strong name/title treatment.',
    composition: 'Asymmetric columns, selected project highlights, concise career timeline.',
    palette: 'Neutral base with one expressive accent.',
    surfaces: 'Use lines, framing, and image placement instead of generic cards.',
    imagery: 'Work samples may be prominent.',
    tables: 'Usually avoided.',
    avoid: 'Generic infographic resume, skill meters, excessive icons.',
  },
  {
    id: 'luxury-editorial',
    name: 'Luxury Editorial',
    family: 'luxury',
    tags: ['luxury','premium','fashion','beauty','editorial','elegant','classy','sober','refined'],
    summary: 'Sparse, premium, highly controlled layout with sophisticated typography and deliberate negative space.',
    typography: 'Refined serif or serif/sans pairing; large scale contrasts; restrained labels.',
    composition: 'Few elements per page, asymmetric balance, generous margins, strong image/type relationships.',
    palette: 'Ivory/white/black with one muted metallic, burgundy, forest, or deep navy accent.',
    surfaces: 'Avoid conventional cards; use whitespace, fine rules, and image crops.',
    imagery: 'Large, art-directed, and integral to composition.',
    tables: 'Rare and extremely restrained.',
    avoid: 'Bright SaaS blue, rainbow accents, rounded boxes, dense dashboard layouts.',
  },
  {
    id: 'fashion-magazine',
    name: 'Fashion / Culture Magazine',
    family: 'editorial',
    tags: ['fashion','magazine','culture','editorial','feature','style','creative'],
    summary: 'Expressive editorial layout with strong photography, typographic contrast, and asymmetry.',
    typography: 'Display serif/sans contrasts; captions and pull quotes used deliberately.',
    composition: 'Image-led spreads, overlapping alignment zones, columns, strong crops, occasional full-bleed moments.',
    palette: 'Content-led; usually restrained around photography.',
    surfaces: 'Minimal cards; use editorial framing.',
    imagery: 'Primary structural element.',
    tables: 'Rare.',
    avoid: 'Corporate dashboard geometry, uniform cards, excessive box borders.',
  },
  {
    id: 'architecture-portfolio',
    name: 'Architecture / Design Portfolio',
    family: 'portfolio',
    tags: ['architecture','portfolio','design','project','case study','interior','visual'],
    summary: 'Grid-conscious visual portfolio with disciplined whitespace and strong project imagery.',
    typography: 'Neutral sans, small labels, strong project titles.',
    composition: 'Large images, precise grids, plans/diagrams, restrained captions.',
    palette: 'Monochrome or material-inspired muted palette.',
    surfaces: 'Minimal boxes.',
    imagery: 'Dominant; plans, elevations, renders, photography.',
    tables: 'Only technical schedules where needed.',
    avoid: 'SaaS cards, decorative gradients, unrelated icons.',
  },
  {
    id: 'museum-cultural',
    name: 'Museum / Cultural Publication',
    family: 'cultural',
    tags: ['museum','culture','history','exhibition','art','heritage','catalogue'],
    summary: 'Thoughtful cultural-publication aesthetic balancing scholarship, imagery, captions, and editorial rhythm.',
    typography: 'Serif-led or distinctive institutional pairing; elegant captions and labels.',
    composition: 'Image/text interplay, generous margins, section openers, occasional archival framing.',
    palette: 'Muted, artwork-led, or institution-specific.',
    surfaces: 'Minimal; use rules, captions, and space.',
    imagery: 'Prominent and carefully captioned.',
    tables: 'Rare, quiet when necessary.',
    avoid: 'Corporate tiles, startup motifs, generic infographics.',
  },
  {
    id: 'newspaper-broadsheet',
    name: 'Newspaper / Broadsheet',
    family: 'editorial',
    tags: ['newspaper','news','broadsheet','article','journalism','press'],
    summary: 'Dense but ordered editorial layout with columns, strong headlines, deck text, rules, and restrained graphics.',
    typography: 'Headline serif or bold sans with highly readable text face.',
    composition: 'Multi-column text, hierarchy through headline/deck/byline/rules, selective sidebars.',
    palette: 'Mostly monochrome, optional spot colour.',
    surfaces: 'No dashboard cards.',
    imagery: 'News photography, charts, captions.',
    tables: 'Compact and factual.',
    avoid: 'Rounded UI components, generous empty luxury spacing, gradients.',
  },
  {
    id: 'book-essay',
    name: 'Book / Long-form Essay',
    family: 'editorial',
    tags: ['book','essay','longform','literary','chapter','prose'],
    summary: 'Reading-first long-form typesetting with literary restraint and excellent text rhythm.',
    typography: 'Serif body, restrained display treatment, careful leading and measure.',
    composition: 'Text-led with chapter/section openers, pull quotes or figures sparingly.',
    palette: 'Black/ivory with minimal accent.',
    surfaces: 'Almost none.',
    imagery: 'Occasional full/half-page figure with caption.',
    tables: 'Rare.',
    avoid: 'Cards, dashboard components, excessive headings, visual noise.',
  },
  {
    id: 'modern-textbook',
    name: 'Modern Textbook',
    family: 'education',
    tags: ['textbook','education','learning','lesson','school','course','training'],
    summary: 'Highly structured educational layout balancing explanatory text, examples, diagrams, and review elements.',
    typography: 'Friendly sans/serif hierarchy with clear labels.',
    composition: 'Learning objectives, examples, diagrams, side notes, exercises, and recap sections.',
    palette: 'Clear but not childish; 1–3 coordinated accents.',
    surfaces: 'Use boxes purposefully for examples, definitions, and activities.',
    imagery: 'Instructional diagrams and illustrations.',
    tables: 'Clear, readable, pedagogical.',
    avoid: 'Corporate report tone, excessive formality, decorative visuals without teaching value.',
  },
  {
    id: 'children-worksheet',
    name: 'Children’s Worksheet',
    family: 'education',
    tags: ['children','kids','worksheet','school','activity','phonics','primary','classroom'],
    summary: 'Approachable, spacious, activity-oriented page with obvious zones and age-appropriate visual cues.',
    typography: 'Large, friendly, highly legible; clear instructions.',
    composition: 'Distinct activity areas, generous writing space, large illustrations, simple sequencing.',
    palette: 'Warm, cheerful, coordinated colours.',
    surfaces: 'Rounded activity boxes are appropriate here.',
    imagery: 'Friendly illustrations and icons can be prominent.',
    tables: 'Simple and large when needed.',
    avoid: 'Dense adult report layouts, tiny type, muted corporate styling.',
  },
  {
    id: 'scientific-report',
    name: 'Scientific Report',
    family: 'scientific',
    tags: ['science','scientific','lab','experiment','research','data','biology','chemistry','physics'],
    summary: 'Evidence-led scientific communication with clean figures, methods/results hierarchy, and disciplined visual language.',
    typography: 'Serif or neutral sans body; restrained headings; figure captions carefully styled.',
    composition: 'Abstract/summary, methods, results, figures/tables, discussion.',
    palette: 'Mostly neutral with controlled scientific accent colours.',
    surfaces: 'Avoid cards; use figure panels and notes only when substantive.',
    imagery: 'Charts, diagrams, microscopy/technical imagery.',
    tables: 'Publication-style, precise, readable.',
    avoid: 'Marketing aesthetic, gradients, decorative hero art.',
  },
  {
    id: 'health-information',
    name: 'Healthcare Information Sheet',
    family: 'health',
    tags: ['health','medical','patient','clinic','hospital','information','care'],
    summary: 'Calm, trustworthy, accessible information design prioritizing comprehension and safety.',
    typography: 'Highly legible sans; clear headings; generous line spacing.',
    composition: 'Short sections, steps, warnings, checklists, and simple diagrams.',
    palette: 'White with calm blue/green accents; accessible contrast.',
    surfaces: 'Use boxes for warnings/actions, not decoration.',
    imagery: 'Simple explanatory visuals.',
    tables: 'Large, accessible, clear.',
    avoid: 'Luxury/editorial ambiguity, tiny text, overly playful visuals.',
  },
  {
    id: 'ngo-impact-report',
    name: 'NGO / Impact Report',
    family: 'nonprofit',
    tags: ['ngo','nonprofit','impact','charity','community','social','report'],
    summary: 'Human-centered impact publication mixing narrative, evidence, key figures, and selective storytelling.',
    typography: 'Warm professional sans/serif pairing.',
    composition: 'Stories, impact figures, quotes, outcomes, concise tables/charts.',
    palette: 'Mission-aligned but restrained.',
    surfaces: 'Metric panels and quotes may be used selectively.',
    imagery: 'Human photography or documentary illustration.',
    tables: 'Simple and accessible.',
    avoid: 'Cold software-dashboard look, excessive corporate polish.',
  },
  {
    id: 'sustainability-esg',
    name: 'Sustainability / ESG Report',
    family: 'corporate',
    tags: ['sustainability','esg','climate','environment','impact','renewable','report'],
    summary: 'Contemporary report aesthetic balancing credibility, environmental imagery, metrics, and structured narrative.',
    typography: 'Professional sans with clear metric hierarchy.',
    composition: 'Narrative sections, metric highlights, charts, goals, progress tables.',
    palette: 'Natural greens/teals/navy with neutral base; avoid cliché overload.',
    surfaces: 'Use metrics panels sparingly.',
    imagery: 'Landscape, infrastructure, or data visualizations.',
    tables: 'Clear targets/progress structures.',
    avoid: 'Every element green, leaf-icon clichés, startup dashboard feel.',
  },
  {
    id: 'product-datasheet',
    name: 'Product Datasheet',
    family: 'product',
    tags: ['datasheet','product','specification','specs','hardware','software','features'],
    summary: 'Compact, highly scannable product communication focused on specifications and value.',
    typography: 'Neutral sans; product name and key specs emphasized.',
    composition: 'Hero/product area, concise benefits, specification table, compatibility/use cases.',
    palette: 'Brand-aware and controlled.',
    surfaces: 'Feature blocks may be used but should remain compact.',
    imagery: 'Product render/photo or simple technical diagram.',
    tables: 'Prominent and clean.',
    avoid: 'Long essay prose, decorative editorial layouts that obscure specs.',
  },
  {
    id: 'product-launch-brief',
    name: 'Product Launch Brief',
    family: 'product',
    tags: ['product','launch','brief','marketing','go-to-market','campaign'],
    summary: 'High-energy but disciplined launch document with strong hierarchy, product framing, and clear action sections.',
    typography: 'Bold sans display with neutral body.',
    composition: 'Hero, positioning, audience, message pillars, launch plan, milestones.',
    palette: 'Brand-led with one or two energetic accents.',
    surfaces: 'Cards are acceptable for message pillars or milestones, but avoid tile overload.',
    imagery: 'Product/brand visuals can be prominent.',
    tables: 'Timelines/milestones should be clear.',
    avoid: 'Generic SaaS aesthetic when brand direction is absent.',
  },
  {
    id: 'saas-product',
    name: 'SaaS / Product Report',
    family: 'digital',
    tags: ['saas','software','startup','product','dashboard','technology','app'],
    summary: 'Contemporary digital-product aesthetic with modular structure, crisp sans typography, and selective colour.',
    typography: 'Modern sans, strong headline hierarchy, compact labels.',
    composition: 'Hero band, product cards, process flows, metrics, feature comparisons.',
    palette: 'Brand-like accent system; gradients permissible when requested.',
    surfaces: 'Cards, pills, and panels are appropriate but should still be coherent.',
    imagery: 'UI illustrations, generated technology visuals, simple diagrams.',
    tables: 'Clean comparison tables.',
    avoid: 'Using this visual language by default for unrelated professional documents.',
  },
  {
    id: 'startup-pitch-doc',
    name: 'Startup Pitch-style Document',
    family: 'digital',
    tags: ['startup','pitch','investor','fundraising','venture','deck','business'],
    summary: 'Concise, high-contrast, outcome-driven document borrowing from pitch-deck logic without becoming slides.',
    typography: 'Bold sans, large key statements, concise supporting copy.',
    composition: 'Problem/opportunity/solution/traction/next steps with strong visual breaks.',
    palette: 'Brand-led, limited, high contrast.',
    surfaces: 'Metric panels and comparison blocks may be prominent.',
    imagery: 'Product visuals and diagrams.',
    tables: 'Sparse, decision-oriented.',
    avoid: 'Dense report prose, too many minor sections.',
  },
  {
    id: 'financial-report',
    name: 'Financial / Investor Report',
    family: 'finance',
    tags: ['financial','finance','investor','earnings','revenue','budget','analysis','market'],
    summary: 'Credible, precise financial publication prioritizing numbers, tables, and interpretive hierarchy.',
    typography: 'Professional sans/serif; tabular numerals where possible.',
    composition: 'Executive summary, key metrics, trends, tables/charts, commentary.',
    palette: 'Neutral with one conservative accent; green/red only when semantically meaningful.',
    surfaces: 'Metric callouts used selectively.',
    imagery: 'Charts over illustrations.',
    tables: 'Central, aligned, precise, understated.',
    avoid: 'Decorative gradients, playful icons, excessive colour.',
  },
  {
    id: 'case-study',
    name: 'Professional Case Study',
    family: 'business',
    tags: ['case study','project','client','problem','solution','results','portfolio'],
    summary: 'Narrative business case with strong before/after logic, evidence, and selective visual proof.',
    typography: 'Professional sans; section headings concise.',
    composition: 'Context, challenge, approach, solution, result; side metrics/quotes as accents.',
    palette: 'Neutral plus brand/project accent.',
    surfaces: 'One or two metric/quote callouts, not a grid of cards.',
    imagery: 'Project imagery/screenshots may lead sections.',
    tables: 'Only if outcomes/specs benefit.',
    avoid: 'Generic consulting slides copied into PDF form.',
  },
  {
    id: 'proposal',
    name: 'Professional Proposal',
    family: 'business',
    tags: ['proposal','client','scope','services','project','quote','offer','business'],
    summary: 'Persuasive but restrained proposal with clear scope, value, deliverables, timeline, and commercial information.',
    typography: 'Professional sans or serif/sans pair.',
    composition: 'Opening proposition, understanding, approach, deliverables, timeline, fees/terms.',
    palette: 'Brand-aware and restrained.',
    surfaces: 'Use structured panels for scope/timeline/pricing only.',
    imagery: 'Relevant project imagery optional.',
    tables: 'Strong for scope, timeline, fees.',
    avoid: 'Pitch-deck hype, decorative boxes around every paragraph.',
  },
  {
    id: 'board-memo',
    name: 'Board / Executive Memo',
    family: 'business',
    tags: ['board','executive','memo','decision','leadership','recommendation','brief'],
    summary: 'Dense but highly scannable decision document for senior readers.',
    typography: 'Neutral sans, strong title, concise section heads.',
    composition: 'Decision/request first, key facts, options, risks, recommendation, appendix if needed.',
    palette: 'Mostly monochrome with one dark accent.',
    surfaces: 'Use one takeaway box or option matrix if useful.',
    imagery: 'Rare; charts only if decision-relevant.',
    tables: 'Compact decision/option tables.',
    avoid: 'Marketing visuals, oversized hero areas, decorative cards.',
  },
  {
    id: 'monochrome-premium',
    name: 'Monochrome Premium',
    family: 'minimal',
    tags: ['monochrome','black','white','minimal','premium','sober','classy','refined'],
    summary: 'High-end black-and-white visual system where proportion and typography do all the work.',
    typography: 'Strong type hierarchy, refined spacing, no reliance on colour.',
    composition: 'Asymmetric layouts, fine rules, occasional black fields, generous but controlled whitespace.',
    palette: 'Black, white, greys only.',
    surfaces: 'Very few containers.',
    imagery: 'Black-and-white or desaturated imagery if used.',
    tables: 'Fine rules, minimal fills.',
    avoid: 'Colour accents, gradients, rounded UI cards, decorative icons.',
  },
  {
    id: 'brutalist-editorial',
    name: 'Brutalist Editorial',
    family: 'experimental',
    tags: ['brutalist','experimental','bold','creative','poster','editorial'],
    summary: 'Raw, deliberately unconventional visual language with hard edges, oversized type, and strong contrast.',
    typography: 'Heavy grotesk/mono/display combinations; scale can be extreme.',
    composition: 'Unexpected alignments, hard rules, visible grid tension, deliberate asymmetry.',
    palette: 'Black/white plus one aggressive accent.',
    surfaces: 'Hard-edged blocks, no soft shadows.',
    imagery: 'High-contrast crops, technical or raw imagery.',
    tables: 'Functional but visually forceful.',
    avoid: 'Soft corporate cards, pastel SaaS polish, generic elegance.',
  },
  {
    id: 'retro-archival',
    name: 'Retro / Archival',
    family: 'experimental',
    tags: ['retro','archival','vintage','history','heritage','nostalgia'],
    summary: 'Period-informed publication aesthetic using archival rhythm without sacrificing readability.',
    typography: 'Period-appropriate serif/sans combinations used carefully.',
    composition: 'Archival captions, framed images, document-like sections, period-inspired rules.',
    palette: 'Paper tones, black, muted heritage colours.',
    surfaces: 'Flat frames/rules rather than modern cards.',
    imagery: 'Archival scans, photography, ephemera.',
    tables: 'Simple, period-neutral.',
    avoid: 'Modern SaaS styling, neon gradients, glossy surfaces.',
  },
  {
    id: 'playful-geometric',
    name: 'Playful Geometric',
    family: 'experimental',
    tags: ['playful','geometric','creative','colourful','youth','event','brand'],
    summary: 'Energetic graphic system using bold geometry and colour with a disciplined underlying grid.',
    typography: 'Bold friendly sans; expressive hierarchy.',
    composition: 'Shapes, offset blocks, dynamic but controlled sections.',
    palette: '2–4 coordinated bright colours.',
    surfaces: 'Graphic blocks are intentional, not generic cards.',
    imagery: 'Illustrations or bold crops.',
    tables: 'Simplify heavily.',
    avoid: 'Muted corporate seriousness, tiny dense type.',
  },
  {
    id: 'image-led-brochure',
    name: 'Image-led Brochure',
    family: 'brochure',
    tags: ['brochure','travel','hospitality','real estate','tourism','image','photography'],
    summary: 'Visual brochure where large imagery and concise copy establish mood and information hierarchy.',
    typography: 'Elegant display heading plus highly readable supporting text.',
    composition: 'Large image zones, short text blocks, feature lists, selective full-width moments.',
    palette: 'Derived from imagery/brand.',
    surfaces: 'Minimal cards; captions and overlays may be used carefully.',
    imagery: 'Primary design element.',
    tables: 'Rare; use only for rates/specs.',
    avoid: 'Text-heavy whitepaper layout, generic dashboards.',
  },
  {
    id: 'travel-editorial',
    name: 'Travel Editorial',
    family: 'editorial',
    tags: ['travel','destination','tourism','guide','itinerary','editorial','city'],
    summary: 'Magazine-like travel document combining place imagery, maps, practical information, and narrative.',
    typography: 'Editorial serif/sans pairing; strong location titles.',
    composition: 'Image-led opener, columns, itinerary blocks, maps/notes, practical footer information.',
    palette: 'Location-derived and restrained.',
    surfaces: 'Use practical info boxes sparingly.',
    imagery: 'Prominent photography/maps.',
    tables: 'Schedules only when helpful.',
    avoid: 'Corporate report styling, repetitive cards.',
  },
  {
    id: 'high-density-reference',
    name: 'High-density Reference',
    family: 'reference',
    tags: ['reference','cheatsheet','manual','guide','dense','quick reference','handbook'],
    summary: 'Compact, information-rich reference document optimized for scanning rather than leisurely reading.',
    typography: 'Small but legible sans; strong heading/label system.',
    composition: 'Columns, compact tables, grouped lists, consistent section rhythm.',
    palette: 'Mostly neutral with semantic accent colours.',
    surfaces: 'Light section framing if needed.',
    imagery: 'Small diagrams/icons only where functional.',
    tables: 'Frequent and compact.',
    avoid: 'Large empty hero areas, oversized headings, decorative whitespace.',
  },
  {
    id: 'sparse-premium-onepager',
    name: 'Sparse Premium One-pager',
    family: 'minimal',
    tags: ['onepager','one-pager','premium','minimal','sparse','executive','overview'],
    summary: 'Very selective content with strong hierarchy, generous white space, and a single clear visual idea.',
    typography: 'Large confident title, restrained body, fine labels.',
    composition: 'One major message, 2–4 supporting zones, minimal footer.',
    palette: 'Neutral with one deep accent.',
    surfaces: 'Avoid cards unless one comparison genuinely needs them.',
    imagery: 'One strong illustration/photo/diagram at most.',
    tables: 'Usually avoid.',
    avoid: 'Trying to fill every inch, multiple competing modules.',
  },
  {
    id: 'data-storytelling',
    name: 'Data Storytelling',
    family: 'data',
    tags: ['data','analytics','metrics','chart','statistics','insight','analysis'],
    summary: 'Narrative data publication where charts and annotated findings lead the reader through an argument.',
    typography: 'Neutral sans with strong chart labels and concise narrative heads.',
    composition: 'Insight headline, chart, annotation, interpretation; repeat with variation rather than identical cards.',
    palette: 'Neutral base with semantic chart colours.',
    surfaces: 'Minimal UI framing.',
    imagery: 'Charts are the imagery.',
    tables: 'Supplementary, clean, aligned.',
    avoid: 'Dashboard screenshot aesthetic, unnecessary decorative illustrations.',
  },
  {
    id: 'infographic-explainer',
    name: 'Infographic Explainer',
    family: 'data',
    tags: ['infographic','explainer','process','diagram','overview','visual'],
    summary: 'Visual-first explanatory document using diagrams, sequences, and annotated concepts.',
    typography: 'Clear sans; concise labels and short body copy.',
    composition: 'Strong flow diagrams, annotated figures, icon-supported sections, clear sequence.',
    palette: '2–3 coordinated accents plus neutral base.',
    surfaces: 'Graphic grouping is appropriate but should not become a generic card grid.',
    imagery: 'Diagrams are primary.',
    tables: 'Only when a comparison cannot be shown visually.',
    avoid: 'Long prose walls, app-dashboard cards, decorative complexity.',
  },
  {
    id: 'engineering-spec',
    name: 'Engineering Specification',
    family: 'technical',
    tags: ['engineering','specification','requirements','architecture','technical','standard'],
    summary: 'Precise engineering document optimized for traceability, requirements, diagrams, and structured detail.',
    typography: 'Neutral sans/serif with mono labels where useful.',
    composition: 'Numbered sections, requirements tables, diagrams, notes, appendices.',
    palette: 'Mostly monochrome with one technical accent.',
    surfaces: 'Functional note/warning boxes only.',
    imagery: 'Architecture/technical diagrams.',
    tables: 'Core structural element.',
    avoid: 'Marketing visuals, ornamental gradients, playful typography.',
  },
  {
    id: 'instruction-manual',
    name: 'Instruction Manual',
    family: 'reference',
    tags: ['manual','instructions','procedure','how-to','guide','operations','training'],
    summary: 'Step-driven procedural document with clarity, safety, and repeatable visual patterns.',
    typography: 'Highly readable sans; numbered steps prominent.',
    composition: 'Overview, prerequisites, numbered procedure, warnings, troubleshooting.',
    palette: 'Neutral with semantic safety accents.',
    surfaces: 'Use warning/info boxes functionally.',
    imagery: 'Annotated screenshots/diagrams are valuable.',
    tables: 'Troubleshooting/spec tables.',
    avoid: 'Editorial ambiguity, overly decorative composition.',
  },
  {
    id: 'restaurant-menu',
    name: 'Restaurant / Hospitality Menu',
    family: 'hospitality',
    tags: ['restaurant','menu','food','hospitality','cafe','dining'],
    summary: 'Hospitality-focused menu or service document with strong typographic atmosphere and easy scanning.',
    typography: 'Brand-appropriate serif/sans; item names/prices clearly related.',
    composition: 'Category sections, balanced columns, restrained dividers, optional hero imagery.',
    palette: 'Brand/venue driven.',
    surfaces: 'Usually no cards.',
    imagery: 'Optional and curated.',
    tables: 'Avoid formal tables; use aligned pricing.',
    avoid: 'Corporate report styling, generic app UI.',
  },
  {
    id: 'event-programme',
    name: 'Event Programme',
    family: 'events',
    tags: ['event','programme','program','conference','schedule','festival','agenda'],
    summary: 'Schedule-led publication balancing event identity with fast practical scanning.',
    typography: 'Distinct event title, clear times/session labels.',
    composition: 'Hero identity, schedule grid, speaker/session details, practical info.',
    palette: 'Event-brand driven.',
    surfaces: 'Session bands/cards appropriate if schedule benefits.',
    imagery: 'Speaker/event photography optional.',
    tables: 'Schedule tables may be central.',
    avoid: 'Long report prose, excessive decorative panels.',
  },
  {
    id: 'real-estate-brochure',
    name: 'Real Estate Brochure',
    family: 'brochure',
    tags: ['real estate','property','brochure','listing','architecture','home'],
    summary: 'Premium property brochure with image-led composition, clean facts, and restrained luxury cues.',
    typography: 'Elegant serif/sans pairing.',
    composition: 'Large property imagery, location/property facts, features, plans, concise narrative.',
    palette: 'Neutral/material-driven.',
    surfaces: 'Minimal; property facts may use a compact aligned strip.',
    imagery: 'Dominant and high quality.',
    tables: 'Specs only.',
    avoid: 'SaaS cards, colourful process flows, dense business-report layout.',
  },
  {
    id: 'brand-guidelines',
    name: 'Brand Guidelines',
    family: 'brand',
    tags: ['brand','guidelines','identity','logo','typography','colour','style guide'],
    summary: 'Systematic design-document aesthetic demonstrating brand rules with generous visual examples.',
    typography: 'Brand-specific hierarchy.',
    composition: 'Principles, logo use, palette, typography, imagery, examples, do/don’t sections.',
    palette: 'The brand palette itself.',
    surfaces: 'Example frames and swatches are appropriate.',
    imagery: 'Essential.',
    tables: 'Rare.',
    avoid: 'Unrelated visual style that competes with the brand being documented.',
  },
  {
    id: 'creative-agency',
    name: 'Creative Agency Presentation-document',
    family: 'creative',
    tags: ['agency','creative','campaign','marketing','concept','brand','presentation'],
    summary: 'Concept-led creative document with stronger art direction, varied page rhythm, and expressive visual framing.',
    typography: 'Bold display typography balanced by clean supporting text.',
    composition: 'Concept opener, mood/idea moments, varied layouts, image/text interplay.',
    palette: 'Concept-driven; can be expressive.',
    surfaces: 'Avoid repetitive cards; use bespoke graphic moments.',
    imagery: 'Prominent and art-directed.',
    tables: 'Rare.',
    avoid: 'Generic corporate report structure.',
  },
  {
    id: 'minimal-tech-editorial',
    name: 'Minimal Technology Editorial',
    family: 'editorial',
    tags: ['technology','ai','software','editorial','minimal','professional','polished'],
    summary: 'Technology subject matter treated as an editorial publication rather than an app dashboard.',
    typography: 'Strong sans or serif/sans pairing; confident but restrained.',
    composition: 'Editorial title treatment, open prose, one or two diagrams, varied grids, carefully composed comparison/table area.',
    palette: 'Dark navy/charcoal with muted teal, rust, or cobalt accent; mostly white space.',
    surfaces: 'Sparse; diagrams/tables should carry structure before cards.',
    imagery: 'Abstract technical illustrations only if they add atmosphere or explanation.',
    tables: 'Publication-style rather than spreadsheet-like.',
    avoid: 'Blue SaaS hero + four cards + four process cards, rainbow nodes, gratuitous rounded rectangles.',
  },
  {
    id: 'custom',
    name: 'Custom / No Reference',
    family: 'custom',
    tags: ['custom','unique','original'],
    summary: 'No predefined visual language. Derive the design directly from the user’s explicit request and document content.',
    typography: 'Choose intentionally for the task.',
    composition: 'Choose intentionally for the task.',
    palette: 'Choose intentionally for the task.',
    surfaces: 'Choose intentionally for the task.',
    imagery: 'Choose intentionally for the task.',
    tables: 'Choose intentionally for the task.',
    avoid: 'Mechanical imitation of any library reference when it does not fit.',
  },
];

const STOPWORDS = new Set([
  'the','and','for','with','from','into','that','this','about','create','make','generate',
  'return','finished','pdf','document','polished','two','page','pages','please','how','what',
  'using','use','include','multiple','models','model',
]);

function tokenize(value: string): string[] {
  return (value.toLowerCase().match(/[a-z0-9À-ÿ一-龯ぁ-ゔァ-ヴー々〆〤]{2,}/g) || [])
    .filter((token) => !STOPWORDS.has(token));
}

function scoreReference(reference: PdfDesignReference, prompt: string): number {
  const lower = prompt.toLowerCase();
  const promptTokens = new Set(tokenize(prompt));
  let score = 0;

  for (const tag of reference.tags) {
    const tagLower = tag.toLowerCase();
    if (lower.includes(tagLower)) score += tagLower.includes(' ') ? 9 : 6;
    for (const token of tokenize(tagLower)) {
      if (promptTokens.has(token)) score += 2;
    }
  }

  const haystack = `${reference.name} ${reference.family} ${reference.summary}`.toLowerCase();
  for (const token of promptTokens) {
    if (haystack.includes(token)) score += 1;
  }

  return score;
}

const GENERIC_REFERENCE_IDS = [
  'restrained-editorial-brief',
  'minimal-tech-editorial',
  'consulting-strategy',
  'swiss-international',
  'technical-whitepaper',
  'institutional-report',
  'monochrome-premium',
  'custom',
];

export function selectPdfDesignReferences(
  prompt: string,
  limit = 8
): PdfDesignReference[] {
  const ranked = PDF_DESIGN_LIBRARY
    .map((reference) => ({ reference, score: scoreReference(reference, prompt) }))
    .sort((a, b) => b.score - a.score);

  const selected: PdfDesignReference[] = [];
  const seen = new Set<string>();

  for (const item of ranked) {
    if (item.score <= 0) break;
    if (!seen.has(item.reference.id)) {
      selected.push(item.reference);
      seen.add(item.reference.id);
    }
    if (selected.length >= Math.max(3, limit - 2)) break;
  }

  for (const id of GENERIC_REFERENCE_IDS) {
    if (selected.length >= limit) break;
    const reference = PDF_DESIGN_LIBRARY.find((item) => item.id === id);
    if (reference && !seen.has(id)) {
      selected.push(reference);
      seen.add(id);
    }
  }

  return selected.slice(0, limit);
}

function formatReference(reference: PdfDesignReference): string {
  return [
    `[${reference.id}] ${reference.name} — ${reference.summary}`,
    `Typography: ${reference.typography}`,
    `Composition: ${reference.composition}`,
    `Palette: ${reference.palette}`,
    `Surfaces: ${reference.surfaces}`,
    `Imagery: ${reference.imagery}`,
    `Tables: ${reference.tables}`,
    `Avoid: ${reference.avoid}`,
  ].join('\n');
}

export function buildPdfDesignReferenceContext(prompt: string): {
  text: string;
  referenceIds: string[];
} {
  const selected = selectPdfDesignReferences(prompt, 8);
  return {
    referenceIds: selected.map((reference) => reference.id),
    text: [
      'DOCUMENT DESIGN REFERENCE LIBRARY — MOODBOARD, NOT TEMPLATES',
      'The following references were retrieved from Plurilog’s broader design library because they may be relevant to this document request. They can guide both PDF and Word output; each format should use only the visual techniques it supports well.',
      'Use them as visual grammar and art-direction references, not fixed layouts. Choose ONE primary reference and optionally ONE secondary reference to borrow from, or choose Custom / No Reference. You may ignore a retrieved reference if it is a poor fit.',
      'Do not mechanically combine all references, do not try to demonstrate every layout primitive, and do not mention the library or selected references to the user.',
      'The user’s explicit visual instructions always override these references. Cultural/document conventions matter: for example, a Japanese employment document should remain Japanese in visual language rather than being forced into a Western report style.',
      '',
      ...selected.map(formatReference),
    ].join('\n\n'),
  };
}
