import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { SiteHeader } from '@/components/SiteHeader';

export const metadata: Metadata = {
  title: 'Terms of Service · Plurilog',
  description: 'Terms and conditions for using Plurilog.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white text-zinc-900 font-sans selection:bg-amber-100 selection:text-zinc-900">
      {/* Navigation Header */}
      <SiteHeader />

      {/* Main Content Column */}
      <main className="flex-1 bg-tech-grid">
        <div className="max-w-3xl mx-auto w-full px-6 sm:px-8 py-12 sm:py-16">
        <div className="mb-10">
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-zinc-900 mb-2">
            Terms of Service
          </h1>
          <p className="text-xs sm:text-sm text-zinc-400">
            Last updated: August 30, 2026
          </p>
        </div>

        <article className="text-sm sm:text-base text-zinc-600 leading-relaxed space-y-6">
          <p>
            Welcome to Plurilog. By creating an account or using our service, you agree to these terms. Please read them.
          </p>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              What Plurilog Is
            </h2>
            <p>
              Plurilog lets you ask a question and get responses from multiple AI models &mdash; including Google&apos;s Gemini, Anthropic&apos;s Claude, and OpenAI&apos;s ChatGPT &mdash; in a shared, cross-referencing panel discussion, so you can compare perspectives rather than relying on a single answer.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Who Can Use Plurilog
            </h2>
            <p>
              You must be at least 18 years old, or the age of majority in your jurisdiction if that&apos;s higher, to use Plurilog.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Your Account
            </h2>
            <p>
              You&apos;re responsible for keeping your login credentials secure and for all activity that happens under your account. Please provide accurate information when you sign up.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Subscriptions and Billing
            </h2>
            <p>
              New accounts receive a one-time free trial credit, which does not renew. Plurilog Plus is a paid subscription billed at $16/month, which renews automatically until you cancel. You can cancel anytime through your account settings &mdash; your access continues through the end of the period you already paid for. Except where required by law, payments are non-refundable for partial billing periods. We may change our pricing, and will give you reasonable notice before any change affecting your subscription takes effect.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Acceptable Use
            </h2>
            <p>
              You agree not to: use Plurilog for anything illegal, harmful, or fraudulent; attempt to circumvent usage limits, reverse-engineer, resell, or abuse the service; upload content you don&apos;t have the right to share; or use Plurilog to generate content that violates the law or these terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              About AI-Generated Responses
            </h2>
            <p>
              Responses in Plurilog are generated by third-party AI systems, and may sometimes be incorrect, incomplete, or outdated. We don&apos;t independently verify AI-generated content. Nothing provided through Plurilog is legal, medical, financial, tax, or other professional advice. Please independently verify anything important, and consult a qualified professional before making decisions based on it.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Your Content
            </h2>
            <p>
              You retain ownership of the content you submit to Plurilog. By using the service, you grant us a limited license to process and store that content solely to provide the service to you.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Ending Your Use of Plurilog
            </h2>
            <p>
              You may stop using Plurilog or delete your account at any time. We may suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Disclaimers and Limitation of Liability
            </h2>
            <p>
              Plurilog is provided &ldquo;as is,&rdquo; without warranties of any kind. To the fullest extent permitted by law, Plurilog is not liable for indirect, incidental, or consequential damages arising from your use of the service, and our total liability for any claim is limited to the amount you paid us in the 12 months before the claim arose. Some jurisdictions don&apos;t allow these limitations, so they may not fully apply to you.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Changes to These Terms
            </h2>
            <p>
              We may update these terms from time to time. We&apos;ll update the &ldquo;Last updated&rdquo; date above; continuing to use Plurilog after a change means you accept the updated terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Governing Law
            </h2>
            <p>
              These terms are governed by the laws of Canada, without regard to conflict of law principles.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-semibold text-zinc-900 tracking-tight">
              Contact Us
            </h2>
            <p>
              Questions about these terms? Email us at <a href="mailto:plurilog@gmail.com" className="text-zinc-900 underline hover:no-underline font-medium">plurilog@gmail.com</a>.
            </p>
          </section>
        </article>
        </div>
      </main>

      {/* Minimal Footer */}
      <footer className="px-6 sm:px-12 py-6 border-t border-zinc-100 bg-white flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-zinc-400">
        <div className="flex items-center gap-2">
          <div className="w-4 h-4 rounded-md bg-amber-50 border border-amber-200/80 flex items-center justify-center text-amber-900 text-[10px]">
            <span className="font-semibold text-[9px]">P</span>
          </div>
          <span>Plurilog &copy; {new Date().getFullYear()}</span>
        </div>

        <div className="flex items-center gap-4 text-[11px]">
          <Link href="/privacy" className="hover:text-zinc-600 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-zinc-600 transition-colors font-medium text-zinc-600">Terms of Service</Link>
        </div>
      </footer>
    </div>
  );
}
