import { NextResponse } from 'next/server';
import { renderDocx } from '@/utils/docxWriter';

export const runtime = 'nodejs';

export async function GET() {
  if (process.env.VERCEL_ENV !== 'preview') {
    return new NextResponse('Not found', { status: 404 });
  }

  const rendered = renderDocx({
    filename: 'plurilog-docx-smoke.docx',
    title: 'Plurilog DOCX Smoke Test',
    blocks: [
      {
        type: 'paragraph',
        text: 'This Word document was generated by the Plurilog DOCX renderer.',
      },
      {
        type: 'heading',
        level: 2,
        text: 'Structured content',
      },
      {
        type: 'bullets',
        items: ['Paragraphs', 'Headings', 'Lists', 'Tables'],
      },
      {
        type: 'table',
        headers: ['Capability', 'Status'],
        rows: [['DOCX rendering', 'OK'], ['Structured source text', 'OK']],
      },
    ],
  });

  return new NextResponse(new Uint8Array(rendered.buffer), {
    status: 200,
    headers: {
      'Content-Type':
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition':
        'attachment; filename="plurilog-docx-smoke.docx"',
      'Content-Length': String(rendered.buffer.length),
      'Cache-Control': 'no-store',
    },
  });
}
